version: '3.8'

services:
  app:
    build: .
    ports:
      - "7000:7000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./app:/app
    command: npm start

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
